// Comprehensive SAP Enterprise, PP, and EWM Organizational Master Data Dictionary
export const DEFAULT_SAP_PP_ORG_STRUCTURE = {
  title: "SAP PP & EWM Organizational Structure",
  subtitle: "Relationship between enterprise structure, production planning execution, and warehouse management",
  nodes: [
    {
      id: "client",
      type: "client",
      category: "enterprise",
      label: "Client",
      technicalName: "Mandant",
      description: "Highest organizational level in SAP system hierarchy; represents the complete enterprise group.",
      tcode: "SCC4",
      example: "Client 100 / 500 (Production)",
      details: "The Client is an independent legal and organizational unit with separate master records, database tables, and user authorizations. All customizing settings and master data reside within a client.",
      configNote: "Maintained in transaction SCC4. Global client settings dictate cross-client locking and change permissions.",
      level: 0
    },
    {
      id: "company-code",
      type: "companyCode",
      category: "enterprise",
      label: "Company Code",
      technicalName: "Buchungskreis (BUKRS)",
      description: "Smallest organizational unit for which a complete, self-contained set of accounts can be created.",
      tcode: "OX02 / FBZP",
      example: "1000 — Nexus Global Corp",
      details: "Represents an independent legal entity required for external statutory reporting (Balance Sheet, P&L). Assigned directly below the Client and holds local currency and chart of accounts.",
      configNote: "Created via transaction OX02; assigned to Chart of Accounts (OB62) and Fiscal Year Variant (OB29).",
      level: 1
    },
    {
      id: "plant",
      type: "plant",
      category: "enterprise",
      label: "Plant",
      technicalName: "Werk (WERKS)",
      description: "Central operational unit within a company code for manufacturing, materials management, and valuation.",
      tcode: "OX10 / OX18",
      example: "1000 — Production Plant Mannheim",
      details: "The Plant is the core operational entity in SAP PP. It defines valuation areas, material requirements planning (MRP) boundaries, production scheduling parameters, and warehouse assignments.",
      configNote: "Created via OX10; assigned to Company Code via OX18. Valuation area is configured in transaction OX14.",
      level: 2
    },
    // SAP PP Branch Nodes
    {
      id: "mrp-area",
      type: "mrpArea",
      category: "pp",
      branch: "pp",
      label: "MRP Areas",
      technicalName: "Dispositionsbereiche (BERID)",
      description: "Independent planning units within a plant (Plant MRP Area, Storage Location MRP Areas, Subcontractors).",
      tcode: "OMIZ / MD01N",
      example: "1000-STG / 1000-SUB",
      details: "Allows fine-grained material requirements planning for specific shop-floor storage locations or external subcontractors independently from the general plant stock.",
      configNote: "Activated in SPRO under Production -> Material Requirements Planning -> MRP Areas.",
      level: 3
    },
    {
      id: "storage-loc",
      type: "storageLoc",
      category: "pp",
      branch: "pp",
      label: "Storage Locations",
      technicalName: "Lagerorte (LGORT)",
      description: "Physical subdivisions of inventory balances within a Plant (Raw Materials, Staging, Finished Goods).",
      tcode: "OX09 / MMBE",
      example: "0001 (Raw), 0002 (Production Staging)",
      details: "Represents physical storage facilities within a plant where stock quantity and valuation are managed. Storage locations are assigned to EWM warehouse numbers for extended warehouse control.",
      configNote: "Maintained in transaction OX09 under Plant customizing. Flags determine EWM warehouse management link.",
      level: 3
    },
    {
      id: "work-center",
      type: "workCenter",
      category: "pp",
      branch: "pp",
      label: "Work Centers",
      technicalName: "Arbeitsplätze (ARBPL)",
      description: "Machines, assembly lines, or labor groups where production operations and capacity scheduling occur.",
      tcode: "CR01 / CR02 / CR03",
      example: "ASSY-01 — Automated Assembly Line",
      details: "Work Centers define standard cost center links, capacity formulas, scheduling formulas, and available working hours. Routings reference work centers to calculate production operation durations and labor costs.",
      configNote: "Created in transaction CR01 with category (Machine/Person) and cost center allocation.",
      level: 3
    },
    {
      id: "psa-pp",
      type: "psa",
      category: "pp",
      branch: "pp",
      label: "Production Supply Area (PSA)",
      technicalName: "Produktionsversorgungsbereich (PVB)",
      description: "Shop-floor physical staging location directly adjacent to work centers for component consumption.",
      tcode: "PK05 / /SCWM/PSA",
      example: "PSA-LINE-1 — Staging Bay 1",
      details: "The Production Supply Area bridges production bills of material (BOM) with warehouse staging. It defines where components must be delivered by warehouse task prior to production execution.",
      configNote: "Defined in PK05 (ERP) and mapped to EWM storage bins in transaction /SCWM/PSA_BIN.",
      level: 3
    },
    {
      id: "prod-version",
      type: "prodVersion",
      category: "pp",
      branch: "pp",
      label: "Production Versions",
      technicalName: "Fertigungsversionen (VERID)",
      description: "Mandatory master data combining Bill of Materials (BOM) and Routing for a specific validity range.",
      tcode: "C223",
      example: "0001 — Standard Recipe Rev 2",
      details: "In S/4HANA, Production Versions are strictly required for all MRP runs and manufacturing orders. It dictates the exact combination of BOM alternative and routing sequence to be executed.",
      configNote: "Maintained centrally in transaction C223 or material master MRP 4 view.",
      level: 3
    },
    {
      id: "bom-routing",
      type: "bomRouting",
      category: "pp",
      branch: "pp",
      label: "Bills of Material & Routings",
      technicalName: "Stücklisten (STPO) & Arbeitspläne",
      description: "Recipe structure of raw materials/quantities and step-by-step sequential manufacturing operations.",
      tcode: "CS01 / CA01",
      example: "BOM Alt 1 / Routing 5000120",
      details: "BOM defines the quantitative component breakdown; Routings define the sequence of machine steps, labor rates, and milestone confirmation points.",
      configNote: "BOM usage 1 (Production). Routings assigned to task list group and Plant.",
      level: 3
    },
    {
      id: "prod-order",
      type: "prodOrder",
      category: "pp",
      branch: "pp",
      label: "Production & Planned Orders",
      technicalName: "Fertigungsaufträge (AUFNR)",
      description: "Transactional execution orders triggering component staging, machine scheduling, and goods receipt.",
      tcode: "CO01 / CO02 / MD04",
      example: "Order 1000847 — 5,000 EA",
      details: "When released, the Production Order generates reservations, capacity requirements, and initiates EWM staging tasks (via Production Material Request / PMR or outbound delivery).",
      configNote: "Order type parameters defined in transaction OPL8.",
      level: 3
    },
    // SAP EWM Branch Nodes
    {
      id: "warehouse-num",
      type: "warehouseNum",
      category: "ewm",
      branch: "ewm",
      label: "Warehouse Number",
      technicalName: "Lagernummer (LGNUM)",
      description: "Primary organizational unit in Extended Warehouse Management (EWM), linked to Plant & Storage Location.",
      tcode: "/SCWM/MON / SPRO",
      example: "W001 — Central High-Bay Warehouse",
      details: "The Warehouse Number represents the entire physical logistics complex. It is assigned to one or more plant and storage location combinations and contains all storage types, bins, and process workflows.",
      configNote: "Customized under SCM Extended Warehouse Management -> Master Data -> Define Warehouse Number.",
      level: 3
    },
    {
      id: "storage-type",
      type: "storageType",
      category: "ewm",
      branch: "ewm",
      label: "Storage Types",
      technicalName: "Lagertypen (LGTYP)",
      description: "Physical or logical subdivisions of a warehouse (Staging, Goods Receipt, High-Rack, Bulk, Pick Face).",
      tcode: "/SCWM/MON (Storage Type)",
      example: "9010 (GR Area), 9030 (Production Staging)",
      details: "Defines putaway and removal rules, temperature zones, hazardous material parameters, and whether storage bins are actively tracked.",
      configNote: "Defined per warehouse number in SPRO customizing for EWM storage types.",
      level: 4
    },
    {
      id: "storage-section",
      type: "storageSection",
      category: "ewm",
      branch: "ewm",
      label: "Storage Sections",
      technicalName: "Lagerbereiche (LGBER)",
      description: "Subdivision of a storage type grouping bins with similar physical attributes (e.g. Fast/Slow movers).",
      tcode: "/SCWM/MON",
      example: "SEC-01 (Fast Moving)",
      details: "Assists automatic bin determination during putaway strategies based on material weight, turnover velocity, or dimensions.",
      configNote: "Configured under EWM Master Data -> Define Storage Sections.",
      level: 5
    },
    {
      id: "storage-bin",
      type: "storageBin",
      category: "ewm",
      branch: "ewm",
      label: "Storage Bins",
      technicalName: "Lagerplätze (LGPLA)",
      description: "Smallest addressable coordinate unit in the warehouse holding physical stock quants.",
      tcode: "/SCWM/LS01N / /SCWM/MON",
      example: "01-04-A-02 (Aisle-Rack-Shelf-Bin)",
      details: "Represents the exact physical location in space. Quants reside in bins with specific batch, handling unit (HU), and stock type attributes.",
      configNote: "Generated via template in /SCWM/LS10 or created individually in /SCWM/LS01N.",
      level: 6
    },
    {
      id: "activity-area",
      type: "activityArea",
      category: "ewm",
      branch: "ewm",
      label: "Activity Areas & WPT",
      technicalName: "Aktivitätsbereiche & Prozessarten",
      description: "Logical groupings of bins for warehouse activities (Picking, Staging, Putaway, Physical Inventory).",
      tcode: "/SCWM/ACT_AREA",
      example: "AA-STAGE / WPT 2010 (Staging Task)",
      details: "Activity Areas drive warehouse order creation rules and picker routing. Warehouse Process Types (WPT) dictate posting behavior and execution control.",
      configNote: "Maintained in EWM customizing under Master Data -> Activity Areas.",
      level: 4
    }
  ],
  edges: [
    { source: "client", target: "company-code", label: "contains" },
    { source: "company-code", target: "plant", label: "assigns" },
    // Plant to PP branch
    { source: "plant", target: "mrp-area", label: "plans via" },
    { source: "plant", target: "storage-loc", label: "manages stock in" },
    { source: "plant", target: "work-center", label: "hosts capacity at" },
    { source: "plant", target: "psa-pp", label: "supplies shop floor" },
    { source: "plant", target: "prod-version", label: "governs recipes" },
    { source: "prod-version", target: "bom-routing", label: "binds" },
    { source: "bom-routing", target: "prod-order", label: "executes as" },
    // Plant to EWM branch
    { source: "plant", target: "warehouse-num", label: "assigned to" },
    { source: "warehouse-num", target: "storage-type", label: "contains" },
    { source: "storage-type", target: "storage-section", label: "divided into" },
    { source: "storage-section", target: "storage-bin", label: "addresses" },
    { source: "warehouse-num", target: "activity-area", label: "executes via" },
    // Staging Integration bridge
    { source: "psa-pp", target: "warehouse-num", label: "Production supply & staging integration", dashed: true }
  ]
};
